name: Build application on PR
"on": pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Installing Dependencies
        run: npm install
      - name: Building
        run: npm run build
